name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: macos-latest
            name: macOS
          - os: ubuntu-latest
            name: Linux
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 10

      - name: Dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get install ocaml opam

      - name: Dependencies (macOS)
        if: runner.os == 'macOS'
        run: brew install ocaml opam rlwrap
        
      - name: Dependencies (ocaml)
        run: |
          opam init
          opam install menhir

      - name: Build
        run: make -j2

      - name: Run examples
        run: make examples
